apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanister-exporter
  labels:
    app.kubernetes.io/name: kanister-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kanister-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kanister-exporter
    spec:
      serviceAccountName: kanister-exporter
      containers:
        - name: exporter
          image: pmpplatform/kanister-exporter:v1.0.0
          ports:
          - name: metrics
            containerPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kanister-exporter
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
  - kind: Group
    name: system:serviceaccounts:kanister
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kanister-exporter-list
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanister-exporter-list
rules:
  - apiGroups: ["cr.kanister.io"]
    resources: ["actionsets"]
    verbs: ["list"]
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kanister-exporter
  labels:
      app.kubernetes.io/name: kanister-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kanister-exporter
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
